#!/bin/csh
# Usage: build [-n] <version> <release>
# Build ELOG distribution

if ($#argv < 2) then
  echo "Usage: build <version> <release>"
  exit
endif
 
set version = $argv[1]
set release = $argv[2]
set dist = `rpm --eval %{\?dist}`
set dir = /tmp/elog-$version
set archive = elog-$version.tar.gz

# create temporary directory
rm -Rf $dir
mkdir $dir
mkdir $dir/doc
mkdir $dir/src
mkdir $dir/mxml
mkdir $dir/man
mkdir $dir/contrib
mkdir $dir/scripts
mkdir $dir/scripts/ckeditor
mkdir $dir/resources
mkdir $dir/ssl
mkdir $dir/themes
mkdir $dir/themes/default
mkdir $dir/themes/default/icons
mkdir $dir/logbooks/
mkdir $dir/logbooks/demo
mkdir $dir/logbooks/demo/2001

# copy files to archive
unalias cp
cp -p src/*.c $dir/src
cp -p src/*.h $dir/src
cp -p mxml/*.c $dir/mxml
cp -p mxml/*.h $dir/mxml
cp -p Makefile $dir
cp -p elogd.cfg.example $dir/elogd.cfg.example
cp -p COPYING $dir
cp -p README $dir
cp -p elogd.init_template $dir
cp -p elogd.plist $dir
cp -p elogd.service $dir

cp -p doc/* $dir/doc
cp -p man/* $dir/man
cp -p contrib/* $dir/contrib
cp -p -r scripts/* $dir/scripts
cp -p resources/* $dir/resources
cp -p ssl/* $dir/ssl

cp -rp themes/default/* $dir/themes/default
cp -p logbooks/demo/2001/011108a.log $dir/logbooks/demo/2001/

# create elog-x.xx.tar.gz file
echo Creating archive...
tar -czf /tmp/$archive -C /tmp/ elog-$version/

# remove temporary files
rm -Rf $dir

# transfer archive
echo Transfer archive...
mkdir -p ~/rpmbuild/SOURCES && cp /tmp/$archive ~/rpmbuild/SOURCES/elog-$version.tar.gz

# if running on at PSI copy to download area
if (`hostname` == 'elog01.psi.ch') then
  if ( -d ~ritt/html/elog/download/tar ) then
    echo "Copy tar file to download area..."
    cp -v /tmp/$archive ~ritt/html/elog/download/tar/elog-$version-$release.tar.gz
    cp -v /tmp/$archive ~ritt/html/elog/download/tar/elog-latest.tar.gz
    cp -vf doc/ChangeLog ~ritt/html/elog/download/ChangeLog
  endif
endif
rm -f /tmp/$archive

echo Cleanup $version-$release rpms
rm -f ~/rpmbuild/RPMS/*/elog*${version}-${release}*.rpm
rm -f ~/rpmbuild/SRPMS/elog*${version}-${release}*.rpm

# building RPMs
echo Build RPMs...
rpmbuild -ba --define "version ${version}" --define "release ${release}" elog.spec || exit $?

# if running on at PSI copy to download area
if (`hostname` == 'elog01.psi.ch') then
  if ( -d ~ritt/html/elog/download/tar ) then
    echo "Copy rpm file to download area..."
    cp -v ~/rpmbuild/RPMS/x86_64/elog*rpm ~ritt/html/elog/download/RPMS/
    cp -v ~/rpmbuild/RPMS/x86_64/elog-$version-$release${dist}.x86_64.rpm ~ritt/html/elog/download/RPMS/elog-latest${dist}.x86_64.rpm
    cp -v ~/rpmbuild/SRPMS/elog*rpm ~ritt/html/elog/download/SRPMS/
    cp -v ~/rpmbuild/SRPMS/elog-$version-$release${dist}.src.rpm ~ritt/html/elog/download/SRPMS/elog-latest${dist}.src.rpm
  endif
endif
